// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Person struct {
	Name  string  `json:"name"`
	Age   int     `json:"age"`
	Posts []*Post `json:"posts"`
}

type Post struct {
	Title  string  `json:"title"`
	Author *Person `json:"author"`
}

type Time struct {
	UnixTime  int    `json:"unixTime"`
	TimeStamp string `json:"timeStamp"`
}
